/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-09-24 02:57:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class student_002dprofile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.2.8.RELEASE.jar", Long.valueOf(1599718188871L));
    _jspx_dependants.put("jar:file:/C:/Users/Sateesh/Desktop/MyDesktop/MySTSWorkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/mavenweb-forms-validations-secure/WEB-INF/lib/spring-webmvc-5.2.8.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1595299266000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fform_0026_005fmodelAttribute_005fmethod_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005flabel_0026_005fpath;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005finput_0026_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005ferrors_0026_005fpath_005fcssClass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fselect_0026_005fpath;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005foptions_0026_005fitems_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fradiobutton_0026_005fvalue_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fcheckbox_0026_005fvalue_005fpath_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fspring_005fform_0026_005fmodelAttribute_005fmethod_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005flabel_0026_005fpath = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005finput_0026_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005ferrors_0026_005fpath_005fcssClass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005fselect_0026_005fpath = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005foptions_0026_005fitems_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005fradiobutton_0026_005fvalue_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005fcheckbox_0026_005fvalue_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fspring_005fform_0026_005fmodelAttribute_005fmethod_005faction.release();
    _005fjspx_005ftagPool_005fspring_005flabel_0026_005fpath.release();
    _005fjspx_005ftagPool_005fspring_005finput_0026_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005fspring_005ferrors_0026_005fpath_005fcssClass_005fnobody.release();
    _005fjspx_005ftagPool_005fspring_005fselect_0026_005fpath.release();
    _005fjspx_005ftagPool_005fspring_005foptions_0026_005fitems_005fnobody.release();
    _005fjspx_005ftagPool_005fspring_005fradiobutton_0026_005fvalue_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005fspring_005fcheckbox_0026_005fvalue_005fpath_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"ISO-8859-1\">\r\n");
      out.write("\t\t<title>Insert title here</title>\r\n");
      out.write("\t\t<style type=\"text/css\">\r\n");
      out.write("\t\t\t.error{\r\n");
      out.write("\t\t\t\tcolor : red;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<h1>Provide you profile info</h1>\r\n");
      out.write("\t\t<hr/>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t");
      //  spring:form
      org.springframework.web.servlet.tags.form.FormTag _jspx_th_spring_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fspring_005fform_0026_005fmodelAttribute_005fmethod_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
      boolean _jspx_th_spring_005fform_005f0_reused = false;
      try {
        _jspx_th_spring_005fform_005f0.setPageContext(_jspx_page_context);
        _jspx_th_spring_005fform_005f0.setParent(null);
        // /WEB-INF/views/student-profile.jsp(26,2) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_spring_005fform_005f0.setAction("save");
        // /WEB-INF/views/student-profile.jsp(26,2) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_spring_005fform_005f0.setMethod("post");
        // /WEB-INF/views/student-profile.jsp(26,2) name = modelAttribute type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_spring_005fform_005f0.setModelAttribute("student");
        int[] _jspx_push_body_count_spring_005fform_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_spring_005fform_005f0 = _jspx_th_spring_005fform_005f0.doStartTag();
          if (_jspx_eval_spring_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("\t\t\t<div>\r\n");
              out.write("\t\t\t\t<div>");
              if (_jspx_meth_spring_005flabel_005f0(_jspx_th_spring_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fform_005f0))
                return;
              out.write("</div>\r\n");
              out.write("\t\t\t\t<div>\r\n");
              out.write("\t\t\t\t\t");
              if (_jspx_meth_spring_005finput_005f0(_jspx_th_spring_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fform_005f0))
                return;
              out.write("\r\n");
              out.write("\t\t\t\t\t");
              //  spring:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_spring_005ferrors_005f0 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fspring_005ferrors_0026_005fpath_005fcssClass_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_spring_005ferrors_005f0_reused = false;
              try {
                _jspx_th_spring_005ferrors_005f0.setPageContext(_jspx_page_context);
                _jspx_th_spring_005ferrors_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
                // /WEB-INF/views/student-profile.jsp(31,5) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spring_005ferrors_005f0.setPath("name");
                // /WEB-INF/views/student-profile.jsp(31,5) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spring_005ferrors_005f0.setCssClass("error");
                int[] _jspx_push_body_count_spring_005ferrors_005f0 = new int[] { 0 };
                try {
                  int _jspx_eval_spring_005ferrors_005f0 = _jspx_th_spring_005ferrors_005f0.doStartTag();
                  if (_jspx_th_spring_005ferrors_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_spring_005ferrors_005f0[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_spring_005ferrors_005f0.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_spring_005ferrors_005f0.doFinally();
                }
                _005fjspx_005ftagPool_005fspring_005ferrors_0026_005fpath_005fcssClass_005fnobody.reuse(_jspx_th_spring_005ferrors_005f0);
                _jspx_th_spring_005ferrors_005f0_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005ferrors_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005ferrors_005f0_reused);
              }
              out.write("\r\n");
              out.write("\t\t\t\t</div>\r\n");
              out.write("\t\t\t</div>\r\n");
              out.write("\t\t\t</br></br>\r\n");
              out.write("\t\t\t<div>\r\n");
              out.write("\t\t\t\t<div>");
              if (_jspx_meth_spring_005flabel_005f1(_jspx_th_spring_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fform_005f0))
                return;
              out.write("</div>\r\n");
              out.write("\t\t\t\t<div>");
              if (_jspx_meth_spring_005finput_005f1(_jspx_th_spring_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fform_005f0))
                return;
              out.write("</div>\r\n");
              out.write("\t\t\t</div>\r\n");
              out.write("\t\t\t\r\n");
              out.write("\t\t\t</br></br>\r\n");
              out.write("\t\t\t<div>\r\n");
              out.write("\t\t\t\t<div>");
              if (_jspx_meth_spring_005flabel_005f2(_jspx_th_spring_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fform_005f0))
                return;
              out.write("</div>\r\n");
              out.write("\t\t\t\t<div>\r\n");
              out.write("\t\t\t\t\t");
              if (_jspx_meth_spring_005finput_005f2(_jspx_th_spring_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fform_005f0))
                return;
              out.write("\r\n");
              out.write("\t\t\t\t\t");
              //  spring:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_spring_005ferrors_005f1 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fspring_005ferrors_0026_005fpath_005fcssClass_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_spring_005ferrors_005f1_reused = false;
              try {
                _jspx_th_spring_005ferrors_005f1.setPageContext(_jspx_page_context);
                _jspx_th_spring_005ferrors_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
                // /WEB-INF/views/student-profile.jsp(45,5) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spring_005ferrors_005f1.setPath("freePasses");
                // /WEB-INF/views/student-profile.jsp(45,5) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spring_005ferrors_005f1.setCssClass("error");
                int[] _jspx_push_body_count_spring_005ferrors_005f1 = new int[] { 0 };
                try {
                  int _jspx_eval_spring_005ferrors_005f1 = _jspx_th_spring_005ferrors_005f1.doStartTag();
                  if (_jspx_th_spring_005ferrors_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_spring_005ferrors_005f1[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_spring_005ferrors_005f1.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_spring_005ferrors_005f1.doFinally();
                }
                _005fjspx_005ftagPool_005fspring_005ferrors_0026_005fpath_005fcssClass_005fnobody.reuse(_jspx_th_spring_005ferrors_005f1);
                _jspx_th_spring_005ferrors_005f1_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005ferrors_005f1, _jsp_getInstanceManager(), _jspx_th_spring_005ferrors_005f1_reused);
              }
              out.write("\r\n");
              out.write("\t\t\t\t</div>\r\n");
              out.write("\t\t\t</div>\r\n");
              out.write("\t\t\t</br></br>\r\n");
              out.write("\t\t\t<div>\r\n");
              out.write("\t\t\t\t<div>");
              if (_jspx_meth_spring_005flabel_005f3(_jspx_th_spring_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fform_005f0))
                return;
              out.write("</div>\r\n");
              out.write("\t\t\t\t<div>\r\n");
              out.write("\t\t\t\t\t");
              if (_jspx_meth_spring_005finput_005f3(_jspx_th_spring_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fform_005f0))
                return;
              out.write("\r\n");
              out.write("\t\t\t\t\t");
              //  spring:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_spring_005ferrors_005f2 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fspring_005ferrors_0026_005fpath_005fcssClass_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_spring_005ferrors_005f2_reused = false;
              try {
                _jspx_th_spring_005ferrors_005f2.setPageContext(_jspx_page_context);
                _jspx_th_spring_005ferrors_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
                // /WEB-INF/views/student-profile.jsp(53,5) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spring_005ferrors_005f2.setPath("courseCode");
                // /WEB-INF/views/student-profile.jsp(53,5) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spring_005ferrors_005f2.setCssClass("error");
                int[] _jspx_push_body_count_spring_005ferrors_005f2 = new int[] { 0 };
                try {
                  int _jspx_eval_spring_005ferrors_005f2 = _jspx_th_spring_005ferrors_005f2.doStartTag();
                  if (_jspx_th_spring_005ferrors_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_spring_005ferrors_005f2[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_spring_005ferrors_005f2.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_spring_005ferrors_005f2.doFinally();
                }
                _005fjspx_005ftagPool_005fspring_005ferrors_0026_005fpath_005fcssClass_005fnobody.reuse(_jspx_th_spring_005ferrors_005f2);
                _jspx_th_spring_005ferrors_005f2_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005ferrors_005f2, _jsp_getInstanceManager(), _jspx_th_spring_005ferrors_005f2_reused);
              }
              out.write("\r\n");
              out.write("\t\t\t\t</div>\r\n");
              out.write("\t\t\t</div>\r\n");
              out.write("\t\t\t</br></br>\r\n");
              out.write("\t\t\t<div>\r\n");
              out.write("\t\t\t\t<div>");
              if (_jspx_meth_spring_005flabel_005f4(_jspx_th_spring_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fform_005f0))
                return;
              out.write("</div>\r\n");
              out.write("\t\t\t\t<div>\r\n");
              out.write("\t\t\t\t\t");
              if (_jspx_meth_spring_005fselect_005f0(_jspx_th_spring_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fform_005f0))
                return;
              out.write("\r\n");
              out.write("\t\t\t\t</div>\r\n");
              out.write("\t\t\t</div>\r\n");
              out.write("\t\t\t</br></br>\r\n");
              out.write("\t\t\t<div>\r\n");
              out.write("\t\t\t\t<div>");
              if (_jspx_meth_spring_005flabel_005f5(_jspx_th_spring_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fform_005f0))
                return;
              out.write("</div>\r\n");
              out.write("\t\t\t\t<div>\r\n");
              out.write("\t\t\t\t\t");
              if (_jspx_meth_spring_005fradiobutton_005f0(_jspx_th_spring_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fform_005f0))
                return;
              out.write(" Python\r\n");
              out.write("\t\t\t\t\t<br/>\r\n");
              out.write("\t\t\t\t\t");
              if (_jspx_meth_spring_005fradiobutton_005f1(_jspx_th_spring_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fform_005f0))
                return;
              out.write(" Java\r\n");
              out.write("\t\t\t\t\t<br/>\r\n");
              out.write("\t\t\t\t\t");
              if (_jspx_meth_spring_005fradiobutton_005f2(_jspx_th_spring_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fform_005f0))
                return;
              out.write(" C#\r\n");
              out.write("\t\t\t\t\t<br/>\r\n");
              out.write("\t\t\t\t\t");
              if (_jspx_meth_spring_005fradiobutton_005f3(_jspx_th_spring_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fform_005f0))
                return;
              out.write(" Javascript\r\n");
              out.write("\t\t\t\t</div>\r\n");
              out.write("\t\t\t</div>\r\n");
              out.write("\t\t\t</br></br>\r\n");
              out.write("\t\t\t<div>\r\n");
              out.write("\t\t\t\t<div>");
              if (_jspx_meth_spring_005flabel_005f6(_jspx_th_spring_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fform_005f0))
                return;
              out.write("</div>\r\n");
              out.write("\t\t\t\t<div>\r\n");
              out.write("\t\t\t\t\t");
              if (_jspx_meth_spring_005fcheckbox_005f0(_jspx_th_spring_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fform_005f0))
                return;
              out.write(" Linux\r\n");
              out.write("\t\t\t\t\t<br/>\r\n");
              out.write("\t\t\t\t\t");
              if (_jspx_meth_spring_005fcheckbox_005f1(_jspx_th_spring_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fform_005f0))
                return;
              out.write(" Alpine\r\n");
              out.write("\t\t\t\t\t<br/>\r\n");
              out.write("\t\t\t\t\t");
              if (_jspx_meth_spring_005fcheckbox_005f2(_jspx_th_spring_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fform_005f0))
                return;
              out.write(" Mac\r\n");
              out.write("\t\t\t\t\t<br/>\r\n");
              out.write("\t\t\t\t\t");
              if (_jspx_meth_spring_005fcheckbox_005f3(_jspx_th_spring_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fform_005f0))
                return;
              out.write(" Windows\r\n");
              out.write("\t\t\t\t\t\r\n");
              out.write("\t\t\t\t</div>\r\n");
              out.write("\t\t\t</div>\r\n");
              out.write("\t\t\t</br>\r\n");
              out.write("\t\t\t<div>\r\n");
              out.write("\t\t\t\t<div><input type=\"submit\" value=\"Submit\" /></div>\r\n");
              out.write("\t\t\t</div>\r\n");
              out.write("\t\t");
              int evalDoAfterBody = _jspx_th_spring_005fform_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_spring_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_spring_005fform_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_spring_005fform_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_spring_005fform_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fspring_005fform_0026_005fmodelAttribute_005fmethod_005faction.reuse(_jspx_th_spring_005fform_005f0);
        _jspx_th_spring_005fform_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005fform_005f0_reused);
      }
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_spring_005flabel_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:label
    org.springframework.web.servlet.tags.form.LabelTag _jspx_th_spring_005flabel_005f0 = (org.springframework.web.servlet.tags.form.LabelTag) _005fjspx_005ftagPool_005fspring_005flabel_0026_005fpath.get(org.springframework.web.servlet.tags.form.LabelTag.class);
    boolean _jspx_th_spring_005flabel_005f0_reused = false;
    try {
      _jspx_th_spring_005flabel_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005flabel_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
      // /WEB-INF/views/student-profile.jsp(28,9) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005flabel_005f0.setPath("name");
      int[] _jspx_push_body_count_spring_005flabel_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005flabel_005f0 = _jspx_th_spring_005flabel_005f0.doStartTag();
        if (_jspx_eval_spring_005flabel_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("Enter name");
            int evalDoAfterBody = _jspx_th_spring_005flabel_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_spring_005flabel_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005flabel_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005flabel_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005flabel_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005flabel_0026_005fpath.reuse(_jspx_th_spring_005flabel_005f0);
      _jspx_th_spring_005flabel_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005flabel_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005flabel_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005finput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spring_005finput_005f0 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspring_005finput_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_spring_005finput_005f0_reused = false;
    try {
      _jspx_th_spring_005finput_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005finput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
      // /WEB-INF/views/student-profile.jsp(30,5) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005finput_005f0.setPath("name");
      int[] _jspx_push_body_count_spring_005finput_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005finput_005f0 = _jspx_th_spring_005finput_005f0.doStartTag();
        if (_jspx_th_spring_005finput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005finput_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005finput_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005finput_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005finput_0026_005fpath_005fnobody.reuse(_jspx_th_spring_005finput_005f0);
      _jspx_th_spring_005finput_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005finput_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005finput_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005flabel_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:label
    org.springframework.web.servlet.tags.form.LabelTag _jspx_th_spring_005flabel_005f1 = (org.springframework.web.servlet.tags.form.LabelTag) _005fjspx_005ftagPool_005fspring_005flabel_0026_005fpath.get(org.springframework.web.servlet.tags.form.LabelTag.class);
    boolean _jspx_th_spring_005flabel_005f1_reused = false;
    try {
      _jspx_th_spring_005flabel_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spring_005flabel_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
      // /WEB-INF/views/student-profile.jsp(36,9) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005flabel_005f1.setPath("email");
      int[] _jspx_push_body_count_spring_005flabel_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005flabel_005f1 = _jspx_th_spring_005flabel_005f1.doStartTag();
        if (_jspx_eval_spring_005flabel_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("Enter Email");
            int evalDoAfterBody = _jspx_th_spring_005flabel_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_spring_005flabel_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005flabel_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005flabel_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005flabel_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005flabel_0026_005fpath.reuse(_jspx_th_spring_005flabel_005f1);
      _jspx_th_spring_005flabel_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005flabel_005f1, _jsp_getInstanceManager(), _jspx_th_spring_005flabel_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005finput_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spring_005finput_005f1 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspring_005finput_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_spring_005finput_005f1_reused = false;
    try {
      _jspx_th_spring_005finput_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spring_005finput_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
      // /WEB-INF/views/student-profile.jsp(37,9) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005finput_005f1.setPath("email");
      int[] _jspx_push_body_count_spring_005finput_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005finput_005f1 = _jspx_th_spring_005finput_005f1.doStartTag();
        if (_jspx_th_spring_005finput_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005finput_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005finput_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005finput_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005finput_0026_005fpath_005fnobody.reuse(_jspx_th_spring_005finput_005f1);
      _jspx_th_spring_005finput_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005finput_005f1, _jsp_getInstanceManager(), _jspx_th_spring_005finput_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005flabel_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:label
    org.springframework.web.servlet.tags.form.LabelTag _jspx_th_spring_005flabel_005f2 = (org.springframework.web.servlet.tags.form.LabelTag) _005fjspx_005ftagPool_005fspring_005flabel_0026_005fpath.get(org.springframework.web.servlet.tags.form.LabelTag.class);
    boolean _jspx_th_spring_005flabel_005f2_reused = false;
    try {
      _jspx_th_spring_005flabel_005f2.setPageContext(_jspx_page_context);
      _jspx_th_spring_005flabel_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
      // /WEB-INF/views/student-profile.jsp(42,9) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005flabel_005f2.setPath("freePasses");
      int[] _jspx_push_body_count_spring_005flabel_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005flabel_005f2 = _jspx_th_spring_005flabel_005f2.doStartTag();
        if (_jspx_eval_spring_005flabel_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("Enter Free Passes");
            int evalDoAfterBody = _jspx_th_spring_005flabel_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_spring_005flabel_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005flabel_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005flabel_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005flabel_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005flabel_0026_005fpath.reuse(_jspx_th_spring_005flabel_005f2);
      _jspx_th_spring_005flabel_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005flabel_005f2, _jsp_getInstanceManager(), _jspx_th_spring_005flabel_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005finput_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spring_005finput_005f2 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspring_005finput_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_spring_005finput_005f2_reused = false;
    try {
      _jspx_th_spring_005finput_005f2.setPageContext(_jspx_page_context);
      _jspx_th_spring_005finput_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
      // /WEB-INF/views/student-profile.jsp(44,5) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005finput_005f2.setPath("freePasses");
      int[] _jspx_push_body_count_spring_005finput_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005finput_005f2 = _jspx_th_spring_005finput_005f2.doStartTag();
        if (_jspx_th_spring_005finput_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005finput_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005finput_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005finput_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005finput_0026_005fpath_005fnobody.reuse(_jspx_th_spring_005finput_005f2);
      _jspx_th_spring_005finput_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005finput_005f2, _jsp_getInstanceManager(), _jspx_th_spring_005finput_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005flabel_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:label
    org.springframework.web.servlet.tags.form.LabelTag _jspx_th_spring_005flabel_005f3 = (org.springframework.web.servlet.tags.form.LabelTag) _005fjspx_005ftagPool_005fspring_005flabel_0026_005fpath.get(org.springframework.web.servlet.tags.form.LabelTag.class);
    boolean _jspx_th_spring_005flabel_005f3_reused = false;
    try {
      _jspx_th_spring_005flabel_005f3.setPageContext(_jspx_page_context);
      _jspx_th_spring_005flabel_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
      // /WEB-INF/views/student-profile.jsp(50,9) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005flabel_005f3.setPath("courseCode");
      int[] _jspx_push_body_count_spring_005flabel_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005flabel_005f3 = _jspx_th_spring_005flabel_005f3.doStartTag();
        if (_jspx_eval_spring_005flabel_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("Enter Course Code");
            int evalDoAfterBody = _jspx_th_spring_005flabel_005f3.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_spring_005flabel_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005flabel_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005flabel_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005flabel_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005flabel_0026_005fpath.reuse(_jspx_th_spring_005flabel_005f3);
      _jspx_th_spring_005flabel_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005flabel_005f3, _jsp_getInstanceManager(), _jspx_th_spring_005flabel_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005finput_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spring_005finput_005f3 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspring_005finput_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_spring_005finput_005f3_reused = false;
    try {
      _jspx_th_spring_005finput_005f3.setPageContext(_jspx_page_context);
      _jspx_th_spring_005finput_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
      // /WEB-INF/views/student-profile.jsp(52,5) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005finput_005f3.setPath("courseCode");
      int[] _jspx_push_body_count_spring_005finput_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005finput_005f3 = _jspx_th_spring_005finput_005f3.doStartTag();
        if (_jspx_th_spring_005finput_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005finput_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005finput_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005finput_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005finput_0026_005fpath_005fnobody.reuse(_jspx_th_spring_005finput_005f3);
      _jspx_th_spring_005finput_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005finput_005f3, _jsp_getInstanceManager(), _jspx_th_spring_005finput_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005flabel_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:label
    org.springframework.web.servlet.tags.form.LabelTag _jspx_th_spring_005flabel_005f4 = (org.springframework.web.servlet.tags.form.LabelTag) _005fjspx_005ftagPool_005fspring_005flabel_0026_005fpath.get(org.springframework.web.servlet.tags.form.LabelTag.class);
    boolean _jspx_th_spring_005flabel_005f4_reused = false;
    try {
      _jspx_th_spring_005flabel_005f4.setPageContext(_jspx_page_context);
      _jspx_th_spring_005flabel_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
      // /WEB-INF/views/student-profile.jsp(58,9) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005flabel_005f4.setPath("country");
      int[] _jspx_push_body_count_spring_005flabel_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005flabel_005f4 = _jspx_th_spring_005flabel_005f4.doStartTag();
        if (_jspx_eval_spring_005flabel_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("Enter Country");
            int evalDoAfterBody = _jspx_th_spring_005flabel_005f4.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_spring_005flabel_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005flabel_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005flabel_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005flabel_005f4.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005flabel_0026_005fpath.reuse(_jspx_th_spring_005flabel_005f4);
      _jspx_th_spring_005flabel_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005flabel_005f4, _jsp_getInstanceManager(), _jspx_th_spring_005flabel_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fselect_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:select
    org.springframework.web.servlet.tags.form.SelectTag _jspx_th_spring_005fselect_005f0 = (org.springframework.web.servlet.tags.form.SelectTag) _005fjspx_005ftagPool_005fspring_005fselect_0026_005fpath.get(org.springframework.web.servlet.tags.form.SelectTag.class);
    boolean _jspx_th_spring_005fselect_005f0_reused = false;
    try {
      _jspx_th_spring_005fselect_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fselect_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
      // /WEB-INF/views/student-profile.jsp(60,5) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fselect_005f0.setPath("country");
      int[] _jspx_push_body_count_spring_005fselect_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fselect_005f0 = _jspx_th_spring_005fselect_005f0.doStartTag();
        if (_jspx_eval_spring_005fselect_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t");
            if (_jspx_meth_spring_005foptions_005f0(_jspx_th_spring_005fselect_005f0, _jspx_page_context, _jspx_push_body_count_spring_005fselect_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t\t");
            out.write("\t\r\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_spring_005fselect_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_spring_005fselect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fselect_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fselect_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fselect_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fselect_0026_005fpath.reuse(_jspx_th_spring_005fselect_005f0);
      _jspx_th_spring_005fselect_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fselect_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005fselect_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005foptions_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fselect_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fselect_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:options
    org.springframework.web.servlet.tags.form.OptionsTag _jspx_th_spring_005foptions_005f0 = (org.springframework.web.servlet.tags.form.OptionsTag) _005fjspx_005ftagPool_005fspring_005foptions_0026_005fitems_005fnobody.get(org.springframework.web.servlet.tags.form.OptionsTag.class);
    boolean _jspx_th_spring_005foptions_005f0_reused = false;
    try {
      _jspx_th_spring_005foptions_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005foptions_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fselect_005f0);
      // /WEB-INF/views/student-profile.jsp(61,6) name = items type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005foptions_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${student.countries}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_spring_005foptions_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005foptions_005f0 = _jspx_th_spring_005foptions_005f0.doStartTag();
        if (_jspx_th_spring_005foptions_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005foptions_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005foptions_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005foptions_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005foptions_0026_005fitems_005fnobody.reuse(_jspx_th_spring_005foptions_005f0);
      _jspx_th_spring_005foptions_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005foptions_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005foptions_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005flabel_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:label
    org.springframework.web.servlet.tags.form.LabelTag _jspx_th_spring_005flabel_005f5 = (org.springframework.web.servlet.tags.form.LabelTag) _005fjspx_005ftagPool_005fspring_005flabel_0026_005fpath.get(org.springframework.web.servlet.tags.form.LabelTag.class);
    boolean _jspx_th_spring_005flabel_005f5_reused = false;
    try {
      _jspx_th_spring_005flabel_005f5.setPageContext(_jspx_page_context);
      _jspx_th_spring_005flabel_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
      // /WEB-INF/views/student-profile.jsp(74,9) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005flabel_005f5.setPath("email");
      int[] _jspx_push_body_count_spring_005flabel_005f5 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005flabel_005f5 = _jspx_th_spring_005flabel_005f5.doStartTag();
        if (_jspx_eval_spring_005flabel_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("Select Favorite Language");
            int evalDoAfterBody = _jspx_th_spring_005flabel_005f5.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_spring_005flabel_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005flabel_005f5[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005flabel_005f5.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005flabel_005f5.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005flabel_0026_005fpath.reuse(_jspx_th_spring_005flabel_005f5);
      _jspx_th_spring_005flabel_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005flabel_005f5, _jsp_getInstanceManager(), _jspx_th_spring_005flabel_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fradiobutton_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:radiobutton
    org.springframework.web.servlet.tags.form.RadioButtonTag _jspx_th_spring_005fradiobutton_005f0 = (org.springframework.web.servlet.tags.form.RadioButtonTag) _005fjspx_005ftagPool_005fspring_005fradiobutton_0026_005fvalue_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.RadioButtonTag.class);
    boolean _jspx_th_spring_005fradiobutton_005f0_reused = false;
    try {
      _jspx_th_spring_005fradiobutton_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fradiobutton_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
      // /WEB-INF/views/student-profile.jsp(76,5) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fradiobutton_005f0.setPath("favoriteLanguage");
      // /WEB-INF/views/student-profile.jsp(76,5) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fradiobutton_005f0.setValue("Python");
      int[] _jspx_push_body_count_spring_005fradiobutton_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fradiobutton_005f0 = _jspx_th_spring_005fradiobutton_005f0.doStartTag();
        if (_jspx_th_spring_005fradiobutton_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fradiobutton_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fradiobutton_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fradiobutton_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fradiobutton_0026_005fvalue_005fpath_005fnobody.reuse(_jspx_th_spring_005fradiobutton_005f0);
      _jspx_th_spring_005fradiobutton_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fradiobutton_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005fradiobutton_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fradiobutton_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:radiobutton
    org.springframework.web.servlet.tags.form.RadioButtonTag _jspx_th_spring_005fradiobutton_005f1 = (org.springframework.web.servlet.tags.form.RadioButtonTag) _005fjspx_005ftagPool_005fspring_005fradiobutton_0026_005fvalue_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.RadioButtonTag.class);
    boolean _jspx_th_spring_005fradiobutton_005f1_reused = false;
    try {
      _jspx_th_spring_005fradiobutton_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fradiobutton_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
      // /WEB-INF/views/student-profile.jsp(78,5) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fradiobutton_005f1.setPath("favoriteLanguage");
      // /WEB-INF/views/student-profile.jsp(78,5) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fradiobutton_005f1.setValue("Java");
      int[] _jspx_push_body_count_spring_005fradiobutton_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fradiobutton_005f1 = _jspx_th_spring_005fradiobutton_005f1.doStartTag();
        if (_jspx_th_spring_005fradiobutton_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fradiobutton_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fradiobutton_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fradiobutton_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fradiobutton_0026_005fvalue_005fpath_005fnobody.reuse(_jspx_th_spring_005fradiobutton_005f1);
      _jspx_th_spring_005fradiobutton_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fradiobutton_005f1, _jsp_getInstanceManager(), _jspx_th_spring_005fradiobutton_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fradiobutton_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:radiobutton
    org.springframework.web.servlet.tags.form.RadioButtonTag _jspx_th_spring_005fradiobutton_005f2 = (org.springframework.web.servlet.tags.form.RadioButtonTag) _005fjspx_005ftagPool_005fspring_005fradiobutton_0026_005fvalue_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.RadioButtonTag.class);
    boolean _jspx_th_spring_005fradiobutton_005f2_reused = false;
    try {
      _jspx_th_spring_005fradiobutton_005f2.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fradiobutton_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
      // /WEB-INF/views/student-profile.jsp(80,5) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fradiobutton_005f2.setPath("favoriteLanguage");
      // /WEB-INF/views/student-profile.jsp(80,5) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fradiobutton_005f2.setValue("C#");
      int[] _jspx_push_body_count_spring_005fradiobutton_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fradiobutton_005f2 = _jspx_th_spring_005fradiobutton_005f2.doStartTag();
        if (_jspx_th_spring_005fradiobutton_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fradiobutton_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fradiobutton_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fradiobutton_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fradiobutton_0026_005fvalue_005fpath_005fnobody.reuse(_jspx_th_spring_005fradiobutton_005f2);
      _jspx_th_spring_005fradiobutton_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fradiobutton_005f2, _jsp_getInstanceManager(), _jspx_th_spring_005fradiobutton_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fradiobutton_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:radiobutton
    org.springframework.web.servlet.tags.form.RadioButtonTag _jspx_th_spring_005fradiobutton_005f3 = (org.springframework.web.servlet.tags.form.RadioButtonTag) _005fjspx_005ftagPool_005fspring_005fradiobutton_0026_005fvalue_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.RadioButtonTag.class);
    boolean _jspx_th_spring_005fradiobutton_005f3_reused = false;
    try {
      _jspx_th_spring_005fradiobutton_005f3.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fradiobutton_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
      // /WEB-INF/views/student-profile.jsp(82,5) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fradiobutton_005f3.setPath("favoriteLanguage");
      // /WEB-INF/views/student-profile.jsp(82,5) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fradiobutton_005f3.setValue("Javascript");
      int[] _jspx_push_body_count_spring_005fradiobutton_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fradiobutton_005f3 = _jspx_th_spring_005fradiobutton_005f3.doStartTag();
        if (_jspx_th_spring_005fradiobutton_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fradiobutton_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fradiobutton_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fradiobutton_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fradiobutton_0026_005fvalue_005fpath_005fnobody.reuse(_jspx_th_spring_005fradiobutton_005f3);
      _jspx_th_spring_005fradiobutton_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fradiobutton_005f3, _jsp_getInstanceManager(), _jspx_th_spring_005fradiobutton_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005flabel_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:label
    org.springframework.web.servlet.tags.form.LabelTag _jspx_th_spring_005flabel_005f6 = (org.springframework.web.servlet.tags.form.LabelTag) _005fjspx_005ftagPool_005fspring_005flabel_0026_005fpath.get(org.springframework.web.servlet.tags.form.LabelTag.class);
    boolean _jspx_th_spring_005flabel_005f6_reused = false;
    try {
      _jspx_th_spring_005flabel_005f6.setPageContext(_jspx_page_context);
      _jspx_th_spring_005flabel_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
      // /WEB-INF/views/student-profile.jsp(87,9) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005flabel_005f6.setPath("email");
      int[] _jspx_push_body_count_spring_005flabel_005f6 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005flabel_005f6 = _jspx_th_spring_005flabel_005f6.doStartTag();
        if (_jspx_eval_spring_005flabel_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("Select your experiences in :");
            int evalDoAfterBody = _jspx_th_spring_005flabel_005f6.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_spring_005flabel_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005flabel_005f6[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005flabel_005f6.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005flabel_005f6.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005flabel_0026_005fpath.reuse(_jspx_th_spring_005flabel_005f6);
      _jspx_th_spring_005flabel_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005flabel_005f6, _jsp_getInstanceManager(), _jspx_th_spring_005flabel_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fcheckbox_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:checkbox
    org.springframework.web.servlet.tags.form.CheckboxTag _jspx_th_spring_005fcheckbox_005f0 = (org.springframework.web.servlet.tags.form.CheckboxTag) _005fjspx_005ftagPool_005fspring_005fcheckbox_0026_005fvalue_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.CheckboxTag.class);
    boolean _jspx_th_spring_005fcheckbox_005f0_reused = false;
    try {
      _jspx_th_spring_005fcheckbox_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fcheckbox_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
      // /WEB-INF/views/student-profile.jsp(89,5) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fcheckbox_005f0.setPath("operatingSystems");
      // /WEB-INF/views/student-profile.jsp(89,5) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fcheckbox_005f0.setValue("Linux");
      int[] _jspx_push_body_count_spring_005fcheckbox_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fcheckbox_005f0 = _jspx_th_spring_005fcheckbox_005f0.doStartTag();
        if (_jspx_th_spring_005fcheckbox_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fcheckbox_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fcheckbox_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fcheckbox_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fcheckbox_0026_005fvalue_005fpath_005fnobody.reuse(_jspx_th_spring_005fcheckbox_005f0);
      _jspx_th_spring_005fcheckbox_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fcheckbox_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005fcheckbox_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fcheckbox_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:checkbox
    org.springframework.web.servlet.tags.form.CheckboxTag _jspx_th_spring_005fcheckbox_005f1 = (org.springframework.web.servlet.tags.form.CheckboxTag) _005fjspx_005ftagPool_005fspring_005fcheckbox_0026_005fvalue_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.CheckboxTag.class);
    boolean _jspx_th_spring_005fcheckbox_005f1_reused = false;
    try {
      _jspx_th_spring_005fcheckbox_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fcheckbox_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
      // /WEB-INF/views/student-profile.jsp(91,5) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fcheckbox_005f1.setPath("operatingSystems");
      // /WEB-INF/views/student-profile.jsp(91,5) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fcheckbox_005f1.setValue("Alpine");
      int[] _jspx_push_body_count_spring_005fcheckbox_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fcheckbox_005f1 = _jspx_th_spring_005fcheckbox_005f1.doStartTag();
        if (_jspx_th_spring_005fcheckbox_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fcheckbox_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fcheckbox_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fcheckbox_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fcheckbox_0026_005fvalue_005fpath_005fnobody.reuse(_jspx_th_spring_005fcheckbox_005f1);
      _jspx_th_spring_005fcheckbox_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fcheckbox_005f1, _jsp_getInstanceManager(), _jspx_th_spring_005fcheckbox_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fcheckbox_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:checkbox
    org.springframework.web.servlet.tags.form.CheckboxTag _jspx_th_spring_005fcheckbox_005f2 = (org.springframework.web.servlet.tags.form.CheckboxTag) _005fjspx_005ftagPool_005fspring_005fcheckbox_0026_005fvalue_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.CheckboxTag.class);
    boolean _jspx_th_spring_005fcheckbox_005f2_reused = false;
    try {
      _jspx_th_spring_005fcheckbox_005f2.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fcheckbox_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
      // /WEB-INF/views/student-profile.jsp(93,5) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fcheckbox_005f2.setPath("operatingSystems");
      // /WEB-INF/views/student-profile.jsp(93,5) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fcheckbox_005f2.setValue("Mac");
      int[] _jspx_push_body_count_spring_005fcheckbox_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fcheckbox_005f2 = _jspx_th_spring_005fcheckbox_005f2.doStartTag();
        if (_jspx_th_spring_005fcheckbox_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fcheckbox_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fcheckbox_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fcheckbox_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fcheckbox_0026_005fvalue_005fpath_005fnobody.reuse(_jspx_th_spring_005fcheckbox_005f2);
      _jspx_th_spring_005fcheckbox_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fcheckbox_005f2, _jsp_getInstanceManager(), _jspx_th_spring_005fcheckbox_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fcheckbox_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_spring_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spring_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:checkbox
    org.springframework.web.servlet.tags.form.CheckboxTag _jspx_th_spring_005fcheckbox_005f3 = (org.springframework.web.servlet.tags.form.CheckboxTag) _005fjspx_005ftagPool_005fspring_005fcheckbox_0026_005fvalue_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.CheckboxTag.class);
    boolean _jspx_th_spring_005fcheckbox_005f3_reused = false;
    try {
      _jspx_th_spring_005fcheckbox_005f3.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fcheckbox_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spring_005fform_005f0);
      // /WEB-INF/views/student-profile.jsp(95,5) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fcheckbox_005f3.setPath("operatingSystems");
      // /WEB-INF/views/student-profile.jsp(95,5) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fcheckbox_005f3.setValue("Windows");
      int[] _jspx_push_body_count_spring_005fcheckbox_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fcheckbox_005f3 = _jspx_th_spring_005fcheckbox_005f3.doStartTag();
        if (_jspx_th_spring_005fcheckbox_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fcheckbox_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fcheckbox_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fcheckbox_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fcheckbox_0026_005fvalue_005fpath_005fnobody.reuse(_jspx_th_spring_005fcheckbox_005f3);
      _jspx_th_spring_005fcheckbox_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fcheckbox_005f3, _jsp_getInstanceManager(), _jspx_th_spring_005fcheckbox_005f3_reused);
    }
    return false;
  }
}
